// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TrainingAndDietApp.Infrastructure.Context;

#nullable disable

namespace TrainingAndDietApp.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240212184611_seedDataChanges2")]
    partial class seedDataChanges2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TrainingAndDietApp.Domain.Entities.Certificate", b =>
                {
                    b.Property<int>("IdCertificate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnOrder(0);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdCertificate"));

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<int>("IdMentor")
                        .HasColumnType("integer");

                    b.Property<bool>("IsAccepted")
                        .HasColumnType("boolean");

                    b.Property<string>("PdfUri")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdCertificate");

                    b.HasIndex("IdMentor");

                    b.ToTable("Certificates");

                    b.HasData(
                        new
                        {
                            IdCertificate = 1,
                            AddedDate = new DateTime(2024, 2, 12, 18, 46, 11, 384, DateTimeKind.Utc).AddTicks(1432),
                            Description = "Certyfikat trenera personalnego.",
                            IdMentor = 1,
                            IsAccepted = true,
                            PdfUri = "febb6cb4-3805-499d-b776-ff493aa35a14.pdf"
                        },
                        new
                        {
                            IdCertificate = 2,
                            AddedDate = new DateTime(2024, 2, 12, 18, 46, 11, 384, DateTimeKind.Utc).AddTicks(1435),
                            Description = "Certyfikat trenera personalnego.",
                            IdMentor = 2,
                            IsAccepted = true,
                            PdfUri = "03f34030-4c42-4f13-935b-35b95963e167.pdf"
                        },
                        new
                        {
                            IdCertificate = 3,
                            AddedDate = new DateTime(2024, 2, 12, 18, 46, 11, 384, DateTimeKind.Utc).AddTicks(1436),
                            Description = "Certyfikat trenera personalnego.",
                            IdMentor = 3,
                            IsAccepted = false,
                            PdfUri = "f8b22ef7-24d4-4ef5-95be-47a1c83479c5.pdf"
                        },
                        new
                        {
                            IdCertificate = 4,
                            AddedDate = new DateTime(2024, 2, 12, 18, 46, 11, 384, DateTimeKind.Utc).AddTicks(1437),
                            Description = "Certyfikat trenera personalnego.",
                            IdMentor = 4,
                            IsAccepted = true,
                            PdfUri = "ab05466b-6a0d-4353-8fd3-03beb4ff53c0.pdf"
                        },
                        new
                        {
                            IdCertificate = 5,
                            AddedDate = new DateTime(2024, 2, 12, 18, 46, 11, 384, DateTimeKind.Utc).AddTicks(1438),
                            Description = "Certyfikat trenera personalnego.",
                            IdMentor = 5,
                            IsAccepted = true,
                            PdfUri = "a811d65d-ea91-4981-ac23-dfd020f888f0.pdf"
                        },
                        new
                        {
                            IdCertificate = 6,
                            AddedDate = new DateTime(2024, 2, 12, 18, 46, 11, 384, DateTimeKind.Utc).AddTicks(1440),
                            Description = "Certyfikat trenera personalnego.",
                            IdMentor = 6,
                            IsAccepted = true,
                            PdfUri = "5ce15f47-5af6-48e1-a995-8163e365f989.pdf"
                        },
                        new
                        {
                            IdCertificate = 7,
                            AddedDate = new DateTime(2024, 2, 12, 18, 46, 11, 384, DateTimeKind.Utc).AddTicks(1441),
                            Description = "Certyfikat zaawansowanego instruktora fitness.",
                            IdMentor = 7,
                            IsAccepted = false,
                            PdfUri = "b8516244-c04b-408f-8825-ceed297744a2.pdf"
                        },
                        new
                        {
                            IdCertificate = 8,
                            AddedDate = new DateTime(2024, 2, 12, 18, 46, 11, 384, DateTimeKind.Utc).AddTicks(1441),
                            Description = "Certyfikat ukończenia specjalistycznego kursu Pilates.",
                            IdMentor = 8,
                            IsAccepted = true,
                            PdfUri = "5a986774-64a5-48ff-93a9-908eedeebb65.pdf"
                        },
                        new
                        {
                            IdCertificate = 9,
                            AddedDate = new DateTime(2024, 2, 12, 18, 46, 11, 384, DateTimeKind.Utc).AddTicks(1442),
                            Description = "Certyfikat ukończenia kursu trenera personalnego.",
                            IdMentor = 9,
                            IsAccepted = true,
                            PdfUri = "03a23944-7156-46ac-8a74-2e918e511d12.pdf"
                        },
                        new
                        {
                            IdCertificate = 10,
                            AddedDate = new DateTime(2024, 2, 12, 18, 46, 11, 384, DateTimeKind.Utc).AddTicks(1444),
                            Description = "Certyfikat dietetyka klinicznego z akredytacją.",
                            IdMentor = 10,
                            IsAccepted = true,
                            PdfUri = "1fa0350a-3d69-4eb5-807c-096983c9f35d.pdf"
                        },
                        new
                        {
                            IdCertificate = 11,
                            AddedDate = new DateTime(2024, 2, 12, 18, 46, 11, 384, DateTimeKind.Utc).AddTicks(1445),
                            Description = "Certyfikat zaawansowanego instruktora fitness.",
                            IdMentor = 11,
                            IsAccepted = false,
                            PdfUri = "fb6e1e39-8404-4095-a2ce-4f47a870e723.pdf"
                        },
                        new
                        {
                            IdCertificate = 12,
                            AddedDate = new DateTime(2024, 2, 12, 18, 46, 11, 384, DateTimeKind.Utc).AddTicks(1446),
                            Description = "Certyfikat ukończenia specjalistycznego kursu Pilates.",
                            IdMentor = 12,
                            IsAccepted = true,
                            PdfUri = "6eb77e22-90ae-46d0-a5be-378a5da63c74.pdf"
                        },
                        new
                        {
                            IdCertificate = 13,
                            AddedDate = new DateTime(2024, 2, 12, 18, 46, 11, 384, DateTimeKind.Utc).AddTicks(1446),
                            Description = "Certyfikat ukończenia kursu trenera personalnego.",
                            IdMentor = 13,
                            IsAccepted = true,
                            PdfUri = "594982e8-d080-4098-9ff4-f857997ac4d6.pdf"
                        },
                        new
                        {
                            IdCertificate = 14,
                            AddedDate = new DateTime(2024, 2, 12, 18, 46, 11, 384, DateTimeKind.Utc).AddTicks(1447),
                            Description = "Certyfikat dietetyka klinicznego z akredytacją.",
                            IdMentor = 14,
                            IsAccepted = true,
                            PdfUri = "0243ab80-01d3-4407-98ee-9019cbd621cd.pdf"
                        },
                        new
                        {
                            IdCertificate = 15,
                            AddedDate = new DateTime(2024, 2, 12, 18, 46, 11, 384, DateTimeKind.Utc).AddTicks(1448),
                            Description = "Certyfikat zaawansowanego instruktora fitness.",
                            IdMentor = 15,
                            IsAccepted = false,
                            PdfUri = "b32cfec6-95c3-4d62-a9a5-3e8eeac16b01.pdf"
                        },
                        new
                        {
                            IdCertificate = 16,
                            AddedDate = new DateTime(2024, 2, 12, 18, 46, 11, 384, DateTimeKind.Utc).AddTicks(1449),
                            Description = "Certyfikat ukończenia specjalistycznego kursu Pilates.",
                            IdMentor = 16,
                            IsAccepted = true,
                            PdfUri = "98a5f8aa-2371-46b7-944f-36962f8470ac.pdf"
                        },
                        new
                        {
                            IdCertificate = 17,
                            AddedDate = new DateTime(2024, 2, 12, 18, 46, 11, 384, DateTimeKind.Utc).AddTicks(1450),
                            Description = "Certyfikat ukończenia kursu trenera personalnego.",
                            IdMentor = 17,
                            IsAccepted = true,
                            PdfUri = "3da44fad-5888-44c9-a716-a5dff7875ff7.pdf"
                        },
                        new
                        {
                            IdCertificate = 18,
                            AddedDate = new DateTime(2024, 2, 12, 18, 46, 11, 384, DateTimeKind.Utc).AddTicks(1451),
                            Description = "Certyfikat dietetyka klinicznego z akredytacją.",
                            IdMentor = 18,
                            IsAccepted = true,
                            PdfUri = "715b3582-14eb-45e8-a33d-6cf8ff679364.pdf"
                        });
                });

            modelBuilder.Entity("TrainingAndDietApp.Domain.Entities.Diet", b =>
                {
                    b.Property<int>("IdDiet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnOrder(0);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdDiet"));

                    b.Property<string>("CustomName")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<int>("IdDietician")
                        .HasColumnType("integer");

                    b.Property<int?>("IdPupil")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<int>("NumberOfWeeks")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("Date");

                    b.Property<int>("TotalKcal")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("IdDiet");

                    b.HasIndex("IdDietician");

                    b.HasIndex("IdPupil");

                    b.ToTable("Diets");
                });

            modelBuilder.Entity("TrainingAndDietApp.Domain.Entities.Exercise", b =>
                {
                    b.Property<int>("IdExercise")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnOrder(0);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdExercise"));

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<string>("ExerciseSteps")
                        .IsRequired()
                        .HasColumnType("varchar(300)");

                    b.Property<int?>("IdTrainer")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("IdExercise");

                    b.HasIndex("IdTrainer");

                    b.ToTable("Exercises");

                    b.HasData(
                        new
                        {
                            IdExercise = 1,
                            Details = "Ćwiczenie na nogi i pośladki",
                            ExerciseSteps = "Stań prosto z nogami rozstawionymi na szerokość barków. Powoli zginaj kolana, zachowując prosty kręgosłup. Schodź do momentu, aż uda będą równolegle do podłogi. Wróć do pozycji wyjściowej.",
                            Name = "Przysiady"
                        },
                        new
                        {
                            IdExercise = 2,
                            Details = "Ćwiczenie na klatkę piersiową, ramiona i tricepsy",
                            ExerciseSteps = "Połóż dłonie na podłodze na szerokość barków. Utrzymaj ciało w prostej linii i opuszczaj się, zginając łokcie, aż klatka piersiowa prawie dotknie podłogi. Wróć do pozycji wyjściowej.",
                            Name = "Pompki"
                        },
                        new
                        {
                            IdExercise = 3,
                            Details = "Ćwiczenie na mięśnie brzucha",
                            ExerciseSteps = "Połóż się na plecach, zegnij kolana i postaw stopy na podłodze. Połóż dłonie za głową. Powoli podnosz tułów do kolan, a następnie powoli opuszczaj się z powrotem.",
                            Name = "Brzuszki"
                        },
                        new
                        {
                            IdExercise = 4,
                            Details = "Ćwiczenie na dolną część pleców, nogi i pośladki",
                            ExerciseSteps = "Stań prosto trzymając sztangę przed sobą. Zginaj biodra i kolana, opuszczając sztangę w dół, aż do momentu, gdy znajdzie się na wysokości goleni. Wróć do pozycji wyjściowej, prostując nogi i biodra.",
                            Name = "Martwy ciąg"
                        },
                        new
                        {
                            IdExercise = 5,
                            Details = "Ćwiczenie na górne partie pleców",
                            ExerciseSteps = "Stań z sztangą trzymaną w obu dłoniach. Pochyl się w biodrach, utrzymując lekki zgięcie w kolanach. Ciągnij sztangę do dolnej części klatki piersiowej, ściągając łopatki. Powoli opuść sztangę z powrotem.",
                            Name = "Wiosłowanie sztangą"
                        });
                });

            modelBuilder.Entity("TrainingAndDietApp.Domain.Entities.Gym", b =>
                {
                    b.Property<int>("IdGym")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnOrder(0);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdGym"));

                    b.Property<int>("AddedBy")
                        .HasColumnType("integer");

                    b.Property<int>("IdAddress")
                        .HasColumnType("integer");

                    b.Property<bool>("IsAccepted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("IdGym");

                    b.HasIndex("IdAddress");

                    b.ToTable("Gyms");

                    b.HasData(
                        new
                        {
                            IdGym = 1,
                            AddedBy = 0,
                            IdAddress = 1,
                            IsAccepted = true,
                            Name = "McFit Wołoska"
                        },
                        new
                        {
                            IdGym = 2,
                            AddedBy = 0,
                            IdAddress = 2,
                            IsAccepted = true,
                            Name = "CityFit Centrum"
                        },
                        new
                        {
                            IdGym = 3,
                            AddedBy = 0,
                            IdAddress = 3,
                            IsAccepted = true,
                            Name = "CityFit Wilanów"
                        });
                });

            modelBuilder.Entity("TrainingAndDietApp.Domain.Entities.Meal", b =>
                {
                    b.Property<int>("IdMeal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnOrder(0);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdMeal"));

                    b.Property<int>("IdDietician")
                        .HasColumnType("integer");

                    b.Property<string>("Ingredients")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Kcal")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("PrepareSteps")
                        .IsRequired()
                        .HasColumnType("varchar(300)");

                    b.HasKey("IdMeal");

                    b.HasIndex("IdDietician");

                    b.ToTable("Meals");
                });

            modelBuilder.Entity("TrainingAndDietApp.Domain.Entities.MealDiet", b =>
                {
                    b.Property<int>("IdMealDiet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnOrder(0);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdMealDiet"));

                    b.Property<string>("Comments")
                        .HasColumnType("varchar(200)");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("integer");

                    b.Property<string>("HourOfMeal")
                        .IsRequired()
                        .HasColumnType("varchar(5)");

                    b.Property<int>("IdDiet")
                        .HasColumnType("integer");

                    b.Property<int>("IdMeal")
                        .HasColumnType("integer");

                    b.HasKey("IdMealDiet");

                    b.HasIndex("IdDiet");

                    b.HasIndex("IdMeal");

                    b.ToTable("Meal_Diets");
                });

            modelBuilder.Entity("TrainingAndDietApp.Domain.Entities.Opinion", b =>
                {
                    b.Property<int>("IdPupil")
                        .HasColumnType("integer");

                    b.Property<int>("IdMentor")
                        .HasColumnType("integer");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("varchar(1000)");

                    b.Property<DateTime>("OpinionDate")
                        .HasColumnType("Date");

                    b.Property<decimal>("Rate")
                        .HasColumnType("decimal(2,1)");

                    b.HasKey("IdPupil", "IdMentor");

                    b.HasIndex("IdMentor");

                    b.ToTable("Opinion");

                    b.HasData(
                        new
                        {
                            IdPupil = 19,
                            IdMentor = 1,
                            Content = "Bardzo profesjonalne podejście do treningu. Czułem się zmotywowany i wspierany przez cały czas. Zdecydowanie polecam tego mentora!",
                            OpinionDate = new DateTime(2024, 2, 12, 18, 46, 11, 384, DateTimeKind.Utc).AddTicks(1682),
                            Rate = 4.5m
                        },
                        new
                        {
                            IdPupil = 20,
                            IdMentor = 1,
                            Content = "Podejście mentora do diety i treningu przekroczyło moje oczekiwania. Indywidualnie dopasowany plan i ciągła motywacja dały świetne wyniki.",
                            OpinionDate = new DateTime(2024, 2, 12, 18, 46, 11, 384, DateTimeKind.Utc).AddTicks(1689),
                            Rate = 5.0m
                        },
                        new
                        {
                            IdPupil = 21,
                            IdMentor = 1,
                            Content = "Trener jest bardzo zaangażowany i posiada ogromną wiedzę. Udało mi się osiągnąć cele, o których wcześniej mogłem tylko marzyć. Polecam z całego serca!",
                            OpinionDate = new DateTime(2024, 2, 12, 18, 46, 11, 384, DateTimeKind.Utc).AddTicks(1690),
                            Rate = 4.8m
                        },
                        new
                        {
                            IdPupil = 19,
                            IdMentor = 10,
                            Content = "Zmiana diety zalecona przez dietetyka znacząco poprawiła moje samopoczucie i wyniki w sporcie. Profesjonalizm i indywidualne podejście do moich potrzeb żywieniowych zrobiły na mnie ogromne wrażenie.",
                            OpinionDate = new DateTime(2024, 2, 12, 18, 46, 11, 384, DateTimeKind.Utc).AddTicks(1691),
                            Rate = 5.0m
                        },
                        new
                        {
                            IdPupil = 20,
                            IdMentor = 8,
                            Content = "Dzięki wskazówkom dietetyka udało mi się nie tylko schudnąć, ale też nauczyłem się, jak zdrowo się odżywiać na co dzień. Bardzo doceniam dostosowanie planu diety do mojego intensywnego trybu życia.",
                            OpinionDate = new DateTime(2024, 2, 12, 18, 46, 11, 384, DateTimeKind.Utc).AddTicks(1692),
                            Rate = 5.0m
                        },
                        new
                        {
                            IdPupil = 21,
                            IdMentor = 9,
                            Content = "Dietetyk pomógł mi zrozumieć, jak ważna jest dieta w moim treningu. Jego/jej wsparcie i motywacja były nieocenione w drodze do osiągnięcia moich celów zdrowotnych. Absolutnie polecam!",
                            OpinionDate = new DateTime(2024, 2, 12, 18, 46, 11, 384, DateTimeKind.Utc).AddTicks(1694),
                            Rate = 4.0m
                        });
                });

            modelBuilder.Entity("TrainingAndDietApp.Domain.Entities.PupilMentor", b =>
                {
                    b.Property<int>("IdMentor")
                        .HasColumnType("integer");

                    b.Property<int>("IdPupil")
                        .HasColumnType("integer");

                    b.Property<bool>("IsAccepted")
                        .HasColumnType("boolean");

                    b.HasKey("IdMentor", "IdPupil");

                    b.HasIndex("IdPupil");

                    b.ToTable("Pupil_mentors");
                });

            modelBuilder.Entity("TrainingAndDietApp.Domain.Entities.TraineeExercise", b =>
                {
                    b.Property<int>("IdTraineeExercise")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnOrder(0);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdTraineeExercise"));

                    b.Property<string>("Comments")
                        .HasColumnType("varchar(200)");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("integer");

                    b.Property<int>("IdExercise")
                        .HasColumnType("integer");

                    b.Property<int>("IdTrainingPlan")
                        .HasColumnType("integer");

                    b.Property<string>("RepetitionsNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SeriesNumber")
                        .HasColumnType("integer");

                    b.HasKey("IdTraineeExercise");

                    b.HasIndex("IdExercise");

                    b.HasIndex("IdTrainingPlan");

                    b.ToTable("Trainee_exercises");
                });

            modelBuilder.Entity("TrainingAndDietApp.Domain.Entities.TrainingPlan", b =>
                {
                    b.Property<int>("IdTrainingPlan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnOrder(0);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdTrainingPlan"));

                    b.Property<string>("CustomName")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("IdPupil")
                        .HasColumnType("integer");

                    b.Property<int>("IdTrainer")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<int>("NumberOfWeeks")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("Date");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("IdTrainingPlan");

                    b.HasIndex("IdPupil");

                    b.HasIndex("IdTrainer");

                    b.ToTable("Training_plans");
                });

            modelBuilder.Entity("TrainingAndDietApp.Domain.Entities.User", b =>
                {
                    b.Property<int>("IdUser")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnOrder(0);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdUser"));

                    b.Property<string>("Bio")
                        .HasColumnType("varchar(1500)");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("Date");

                    b.Property<decimal?>("DietPriceFrom")
                        .HasColumnType("decimal(7,2)");

                    b.Property<decimal?>("DietPriceTo")
                        .HasColumnType("decimal(7,2)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(254)");

                    b.Property<string>("HashedPassword")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("Height")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("IdRole")
                        .HasColumnType("integer");

                    b.Property<string>("ImageUri")
                        .HasColumnType("text");

                    b.Property<bool>("IsAccepted")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<decimal?>("PersonalTrainingPriceFrom")
                        .HasColumnType("decimal(7,2)");

                    b.Property<decimal?>("PersonalTrainingPriceTo")
                        .HasColumnType("decimal(7,2)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("varchar(15)");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("text");

                    b.Property<DateTime?>("RefreshTokenExpirationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Sex")
                        .HasColumnType("varchar(10)");

                    b.Property<decimal?>("TrainingPlanPriceFrom")
                        .HasColumnType("decimal(7,2)");

                    b.Property<decimal?>("TrainingPlanPriceTo")
                        .HasColumnType("decimal(7,2)");

                    b.Property<decimal?>("Weight")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("IdUser");

                    b.HasIndex("IdRole");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            IdUser = 1,
                            Bio = "Pasjonat zdrowego stylu życia i fitnessu. Z ponad 5-letnim doświadczeniem jako trener personalny, pomogłem wielu osobom osiągnąć ich cele zdrowotne i kondycyjne. Specjalizuję się w treningach siłowych, kondycyjnych oraz w doradztwie żywieniowym.",
                            Email = "michal@gmail.com",
                            HashedPassword = "$2a$11$G4BZAf44NMcnVIBSt3GLi.ibHM6eTx.H14jTTWq8YdWGaoqfadP7e",
                            IdRole = 3,
                            ImageUri = "6e067ad6-14a2-43a7-94b5-d145cab0fa95.png",
                            IsAccepted = true,
                            LastName = "Emczyk",
                            Name = "Michał",
                            PersonalTrainingPriceFrom = 100m,
                            PersonalTrainingPriceTo = 150m,
                            PhoneNumber = "+48 777 888 777",
                            TrainingPlanPriceFrom = 200m,
                            TrainingPlanPriceTo = 250m
                        },
                        new
                        {
                            IdUser = 2,
                            Bio = "Ekspertka od jogi i pilatesu z ponad 8-letnim doświadczeniem. Pomogłam setkom osób poprawić ich elastyczność, siłę i zdrowie psychiczne. Moje zajęcia są dostosowane do każdego poziomu zaawansowania.",
                            Email = "anna.kowalska@gmail.com",
                            HashedPassword = "$2a$11$G4BZAf44NMcnVIBSt3GLi.ibHM6eTx.H14jTTWq8YdWGaoqfadP7e",
                            IdRole = 3,
                            ImageUri = "d0202f7d-453f-42fa-b9d9-6c91b68f5ee1.png",
                            IsAccepted = true,
                            LastName = "Kowalska",
                            Name = "Anna",
                            PersonalTrainingPriceFrom = 120m,
                            PersonalTrainingPriceTo = 170m,
                            PhoneNumber = "+48 666 555 444",
                            TrainingPlanPriceFrom = 220m,
                            TrainingPlanPriceTo = 270m
                        },
                        new
                        {
                            IdUser = 3,
                            Bio = "Specjalista od treningu siłowego i crossfitu. Z ponad 10 lat doświadczenia w branży fitness, moim celem jest pomaganie klientom w budowaniu siły, wytrzymałości i pewności siebie.",
                            Email = "jakub.nowak@gmail.com",
                            HashedPassword = "$2a$11$G4BZAf44NMcnVIBSt3GLi.ibHM6eTx.H14jTTWq8YdWGaoqfadP7e",
                            IdRole = 3,
                            ImageUri = "e2d2e547-8d22-4f54-972b-0a474ba02b3e.png ",
                            IsAccepted = true,
                            LastName = "Nowak",
                            Name = "Jakub",
                            PersonalTrainingPriceFrom = 130m,
                            PersonalTrainingPriceTo = 180m,
                            PhoneNumber = "+48 555 444 333",
                            TrainingPlanPriceFrom = 230m,
                            TrainingPlanPriceTo = 280m
                        },
                        new
                        {
                            IdUser = 4,
                            Bio = "Pasjonatka zdrowego żywienia i treningów funkcjonalnych. Z certyfikatem dietetyka i trenera, pomagam moim klientom osiągać cele związane z poprawą kompozycji ciała i samopoczucia.",
                            Email = "ewa.wisniewska@gmail.com",
                            HashedPassword = "$2a$11$G4BZAf44NMcnVIBSt3GLi.ibHM6eTx.H14jTTWq8YdWGaoqfadP7e",
                            IdRole = 3,
                            ImageUri = "64b48343-760f-40b9-b001-52e063e5aab1.png ",
                            IsAccepted = true,
                            LastName = "Wiśniewska",
                            Name = "Ewa",
                            PersonalTrainingPriceFrom = 110m,
                            PersonalTrainingPriceTo = 160m,
                            Sex = "Kobieta",
                            TrainingPlanPriceFrom = 210m,
                            TrainingPlanPriceTo = 260m
                        },
                        new
                        {
                            IdUser = 5,
                            Bio = "Trener boksu i samoobrony z 12-letnim stażem. Specjalizuję się w pracy z ludźmi w każdym wieku, ucząc ich nie tylko technik walki, ale również dyscypliny i szacunku do siebie i innych.",
                            Email = "tomasz.zielinski@gmail.com",
                            HashedPassword = "$2a$11$G4BZAf44NMcnVIBSt3GLi.ibHM6eTx.H14jTTWq8YdWGaoqfadP7e",
                            IdRole = 3,
                            IsAccepted = true,
                            LastName = "Zieliński",
                            Name = "Tomasz",
                            PersonalTrainingPriceFrom = 140m,
                            PersonalTrainingPriceTo = 190m,
                            PhoneNumber = "+48 888 999 000",
                            TrainingPlanPriceFrom = 240m,
                            TrainingPlanPriceTo = 290m
                        },
                        new
                        {
                            IdUser = 6,
                            Bio = "Doświadczony trener personalny i fizjoterapeuta z ponad 10 lat doświadczenia. Specjalizuję się w rehabilitacji sportowej, treningach siłowych i poprawie mobilności. Moje metody pracy są oparte na najnowszych badaniach i dostosowane do indywidualnych potrzeb klientów.",
                            Email = "marcin.dabrowski@gmail.com",
                            HashedPassword = "$2a$11$G4BZAf44NMcnVIBSt3GLi.ibHM6eTx.H14jTTWq8YdWGaoqfadP7e",
                            IdRole = 3,
                            IsAccepted = true,
                            LastName = "Dąbrowski",
                            Name = "Marcin",
                            PersonalTrainingPriceFrom = 150m,
                            PersonalTrainingPriceTo = 200m,
                            PhoneNumber = "+48 111 222 333",
                            TrainingPlanPriceFrom = 250m,
                            TrainingPlanPriceTo = 300m
                        },
                        new
                        {
                            IdUser = 7,
                            Bio = "Dietetyk kliniczny z doświadczeniem w pracy z pacjentami z chorobami metabolicznymi. Specjalizuję się w dietoterapii cukrzycowej, otyłości oraz chorób sercowo-naczyniowych. Moje plany żywieniowe są tworzone na podstawie najnowszych wytycznych naukowych.",
                            DietPriceFrom = 150m,
                            DietPriceTo = 200m,
                            Email = "piotr.wojcik@gmail.com",
                            HashedPassword = "$2a$11$G4BZAf44NMcnVIBSt3GLi.ibHM6eTx.H14jTTWq8YdWGaoqfadP7e",
                            IdRole = 4,
                            ImageUri = "344f5775-e8f2-417d-a884-d297d8f754be.png",
                            IsAccepted = true,
                            LastName = "Wójcik",
                            Name = "Piotr",
                            PhoneNumber = "+48 200 300 400"
                        },
                        new
                        {
                            IdUser = 8,
                            Bio = "Ekspert od dietetyki sportowej z wieloletnim doświadczeniem w pracy z zawodowymi sportowcami. Moje podejście łączy najnowszą wiedzę z zakresu nauk o żywieniu z indywidualnymi potrzebami klienta, aby maksymalizować ich wyniki sportowe.",
                            DietPriceFrom = 160m,
                            DietPriceTo = 210m,
                            Email = "tomasz.lewandowski@gmail.com",
                            HashedPassword = "$2a$11$G4BZAf44NMcnVIBSt3GLi.ibHM6eTx.H14jTTWq8YdWGaoqfadP7e",
                            IdRole = 4,
                            IsAccepted = true,
                            LastName = "Lewandowski",
                            Name = "Tomasz",
                            PhoneNumber = "+48 210 310 410"
                        },
                        new
                        {
                            IdUser = 9,
                            Bio = "Dietetyczka z pasją do pomagania ludziom w zmianie ich nawyków żywieniowych i osiąganiu celów zdrowotnych. Specjalizuję się w dietach wegetariańskich, wegańskich oraz w redukcji wagi.",
                            DietPriceFrom = 120m,
                            DietPriceTo = 170m,
                            Email = "anna.majewska@gmail.com",
                            HashedPassword = "$2a$11$G4BZAf44NMcnVIBSt3GLi.ibHM6eTx.H14jTTWq8YdWGaoqfadP7e",
                            IdRole = 4,
                            ImageUri = "6215d910-8dd4-42f8-ad03-e5b900d1d2bc.png",
                            IsAccepted = true,
                            LastName = "Majewska",
                            Name = "Anna",
                            PhoneNumber = "+48 220 320 420"
                        },
                        new
                        {
                            IdUser = 10,
                            Bio = "Specjalistka od żywienia klinicznego i zdrowego stylu życia. Z doświadczeniem w pracy zarówno z dziećmi, jak i dorosłymi, tworzę spersonalizowane plany żywieniowe, które wspierają zdrowie i dobre samopoczucie.",
                            DietPriceFrom = 130m,
                            DietPriceTo = 180m,
                            Email = "ewa.kubiak@gmail.com",
                            HashedPassword = "$2a$11$G4BZAf44NMcnVIBSt3GLi.ibHM6eTx.H14jTTWq8YdWGaoqfadP7e",
                            IdRole = 4,
                            ImageUri = "ae4e5ae8-d5eb-4f33-9a37-c86ec4558eca.png",
                            IsAccepted = true,
                            LastName = "Kubiak",
                            Name = "Ewa",
                            PhoneNumber = "+48 230 330 430"
                        },
                        new
                        {
                            IdUser = 11,
                            Bio = "Dietetyczka z zamiłowaniem do żywienia dzieci i młodzieży. Moja praca skupia się na edukacji żywieniowej oraz tworzeniu zbilansowanych, smacznych planów żywieniowych, które pomagają młodym ludziom rosnąć zdrowo i szczęśliwie.",
                            DietPriceFrom = 140m,
                            DietPriceTo = 190m,
                            Email = "katarzyna.zawadzka@gmail.com",
                            HashedPassword = "$2a$11$G4BZAf44NMcnVIBSt3GLi.ibHM6eTx.H14jTTWq8YdWGaoqfadP7e",
                            IdRole = 4,
                            IsAccepted = true,
                            LastName = "Zawadzka",
                            Name = "Katarzyna",
                            PhoneNumber = "+48 240 340 440"
                        },
                        new
                        {
                            IdUser = 12,
                            Bio = "Dietetyk specjalizujący się w żywieniu osób starszych i zarządzaniu chorobami przewlekłymi poprzez dietę. Moje podejście to połączenie empatii, wiedzy i dostosowania planów żywieniowych do unikalnych potrzeb każdego klienta.",
                            DietPriceFrom = 150m,
                            DietPriceTo = 200m,
                            Email = "michal.sikora@gmail.com",
                            HashedPassword = "$2a$11$G4BZAf44NMcnVIBSt3GLi.ibHM6eTx.H14jTTWq8YdWGaoqfadP7e",
                            IdRole = 4,
                            ImageUri = "6ebe92cf-ead1-4582-9f96-271be4e69f76.png",
                            IsAccepted = true,
                            LastName = "Sikora",
                            Name = "Michał",
                            PhoneNumber = "+48 250 350 450"
                        },
                        new
                        {
                            IdUser = 13,
                            Bio = "Zawodowy trener i dietetyk z 12-letnim stażem. Specjalizuję się w kompleksowym podejściu do fitnessu i zdrowego odżywiania, łącząc trening siłowy z zbilansowanym planem żywieniowym.",
                            DietPriceFrom = 150m,
                            DietPriceTo = 200m,
                            Email = "krzysztof.borowski@gmail.com",
                            HashedPassword = "$2a$11$G4BZAf44NMcnVIBSt3GLi.ibHM6eTx.H14jTTWq8YdWGaoqfadP7e",
                            IdRole = 5,
                            ImageUri = "abe1a889-83bc-440d-b751-d17244558d7b.png",
                            IsAccepted = true,
                            LastName = "Borowski",
                            Name = "Krzysztof",
                            PersonalTrainingPriceFrom = 200m,
                            PersonalTrainingPriceTo = 250m,
                            PhoneNumber = "+48 300 400 500",
                            TrainingPlanPriceFrom = 300m,
                            TrainingPlanPriceTo = 350m
                        },
                        new
                        {
                            IdUser = 14,
                            Bio = "Ekspert od żywienia i treningu personalnego. Pomagam klientom osiągać ich cele związane z formą fizyczną i zdrowiem poprzez indywidualnie dostosowane plany treningowe i dietetyczne.",
                            DietPriceFrom = 160m,
                            DietPriceTo = 210m,
                            Email = "adam.nowak@gmail.com",
                            HashedPassword = "$2a$11$G4BZAf44NMcnVIBSt3GLi.ibHM6eTx.H14jTTWq8YdWGaoqfadP7e",
                            IdRole = 5,
                            IsAccepted = true,
                            LastName = "Nowak",
                            Name = "Adam",
                            PersonalTrainingPriceFrom = 210m,
                            PersonalTrainingPriceTo = 260m,
                            PhoneNumber = "+48 310 410 510",
                            TrainingPlanPriceFrom = 310m,
                            TrainingPlanPriceTo = 360m
                        },
                        new
                        {
                            IdUser = 15,
                            Bio = "Pasjonatka zdrowego stylu życia, certyfikowana dietetyczka i trenerka personalna. Specjalizuję się w treningach funkcjonalnych i doradztwie żywieniowym dla kobiet.",
                            DietPriceFrom = 130m,
                            DietPriceTo = 180m,
                            Email = "joanna.kubiak@gmail.com",
                            HashedPassword = "$2a$11$G4BZAf44NMcnVIBSt3GLi.ibHM6eTx.H14jTTWq8YdWGaoqfadP7e",
                            IdRole = 5,
                            ImageUri = "cb69da6a-09b6-43f3-88c9-8b77f23d06b5.png",
                            IsAccepted = true,
                            LastName = "Kubiak",
                            Name = "Joanna",
                            PersonalTrainingPriceFrom = 180m,
                            PersonalTrainingPriceTo = 230m,
                            PhoneNumber = "+48 320 420 520",
                            TrainingPlanPriceFrom = 280m,
                            TrainingPlanPriceTo = 330m
                        },
                        new
                        {
                            IdUser = 16,
                            Bio = "Dietetyk i trenerka z miłością do pomagania ludziom w transformacji ich życia. Skupiam się na zrównoważonym żywieniu i efektywnych treningach, które poprawiają kondycję i samopoczucie.",
                            DietPriceFrom = 140m,
                            DietPriceTo = 190m,
                            Email = "magdalena.sikorska@gmail.com",
                            HashedPassword = "$2a$11$G4BZAf44NMcnVIBSt3GLi.ibHM6eTx.H14jTTWq8YdWGaoqfadP7e",
                            IdRole = 5,
                            ImageUri = "44b42606-ca16-4ddc-b552-249cac1f6f34.png",
                            IsAccepted = true,
                            LastName = "Sikorska",
                            Name = "Magdalena",
                            PersonalTrainingPriceFrom = 190m,
                            PersonalTrainingPriceTo = 240m,
                            PhoneNumber = "+48 330 430 530",
                            TrainingPlanPriceFrom = 290m,
                            TrainingPlanPriceTo = 340m
                        },
                        new
                        {
                            IdUser = 17,
                            Bio = "Ekspertka w dziedzinie dietetyki i fitnessu. Oferuję holistyczne podejście do zdrowia, łączące naukowe podejście do odżywiania z indywidualnie dostosowanymi treningami.",
                            DietPriceFrom = 145m,
                            DietPriceTo = 195m,
                            Email = "katarzyna.zawadzka@gmail.com",
                            HashedPassword = "$2a$11$G4BZAf44NMcnVIBSt3GLi.ibHM6eTx.H14jTTWq8YdWGaoqfadP7e",
                            IdRole = 5,
                            ImageUri = "82cbe9a9-6748-4774-a231-895c245e49c0.png",
                            IsAccepted = true,
                            LastName = "Zawadzka",
                            Name = "Katarzyna",
                            PersonalTrainingPriceFrom = 195m,
                            PersonalTrainingPriceTo = 245m,
                            PhoneNumber = "+48 340 440 540",
                            TrainingPlanPriceFrom = 295m,
                            TrainingPlanPriceTo = 345m
                        },
                        new
                        {
                            IdUser = 18,
                            Bio = "Profesjonalny dietetyk-trener, specjalizujący się w przygotowaniach do zawodów sportowych i optymalizacji zdrowia metabolicznego. Moje programy łączą dietetykę sportową z treningiem siłowym i wytrzymałościowym.",
                            DietPriceFrom = 170m,
                            DietPriceTo = 220m,
                            Email = "robert.lewandowski@gmail.com",
                            HashedPassword = "$2a$11$G4BZAf44NMcnVIBSt3GLi.ibHM6eTx.H14jTTWq8YdWGaoqfadP7e",
                            IdRole = 5,
                            IsAccepted = true,
                            LastName = "Lewandowski",
                            Name = "Robert",
                            PersonalTrainingPriceFrom = 220m,
                            PersonalTrainingPriceTo = 270m,
                            PhoneNumber = "+48 350 450 550",
                            TrainingPlanPriceFrom = 320m,
                            TrainingPlanPriceTo = 370m
                        },
                        new
                        {
                            IdUser = 19,
                            Bio = "Amator biegania i triatlonu szukający profesjonalnej pomocy w poprawie wyników i optymalizacji diety.",
                            DateOfBirth = new DateTime(1985, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "michal.kowalski@gmail.com",
                            HashedPassword = "$2a$11$G4BZAf44NMcnVIBSt3GLi.ibHM6eTx.H14jTTWq8YdWGaoqfadP7e",
                            Height = 180m,
                            IdRole = 2,
                            ImageUri = "436006ea-a754-4ad2-b7fb-b7db6a8ecb77.png",
                            IsAccepted = false,
                            LastName = "Kowalski",
                            Name = "Michał",
                            Sex = "Mężczyzna",
                            Weight = 75m
                        },
                        new
                        {
                            IdUser = 20,
                            Bio = "Zaangażowana w zdrowy styl życia, poszukuje wsparcia w zakresie żywienia i planowania treningów, aby osiągnąć lepszą formę i samopoczucie.",
                            DateOfBirth = new DateTime(1990, 8, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "anna.nowak@gmail.com",
                            HashedPassword = "$2a$11$G4BZAf44NMcnVIBSt3GLi.ibHM6eTx.H14jTTWq8YdWGaoqfadP7e",
                            Height = 165m,
                            IdRole = 2,
                            IsAccepted = false,
                            LastName = "Nowak",
                            Name = "Anna",
                            Sex = "Kobieta",
                            Weight = 60m
                        },
                        new
                        {
                            IdUser = 21,
                            Bio = "Pasjonatka jogi i pilatesu, chcąca zwiększyć swoją wiedzę o zdrowym odżywianiu i zintegrować ją z aktywnością fizyczną, by poprawić jakość życia.",
                            DateOfBirth = new DateTime(1995, 3, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "magdalena.wisniewska@gmail.com",
                            HashedPassword = "$2a$11$G4BZAf44NMcnVIBSt3GLi.ibHM6eTx.H14jTTWq8YdWGaoqfadP7e",
                            Height = 170m,
                            IdRole = 2,
                            ImageUri = "089e2d9d-51a4-4b7f-a245-99a1a5e4e729.png",
                            IsAccepted = false,
                            LastName = "Wiśniewska",
                            Name = "Magdalena",
                            Sex = "Kobieta",
                            Weight = 65m
                        },
                        new
                        {
                            IdUser = 22,
                            Email = "admin@gmail.com",
                            HashedPassword = "$2a$11$7aINjux8LPZ6sHPSIHnYme/Xp11oanULdNMUyrUcgGwdAAKHCDIFW",
                            IdRole = 1,
                            IsAccepted = false,
                            LastName = "Admin",
                            Name = "Admin"
                        });
                });

            modelBuilder.Entity("Training_and_diet_backend.Models.Address", b =>
                {
                    b.Property<int>("IdAddress")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnOrder(0);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdAddress"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("char(6)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("IdAddress");

                    b.ToTable("Addresses");

                    b.HasData(
                        new
                        {
                            IdAddress = 1,
                            City = "Warszawa",
                            PostalCode = "02-222",
                            Street = "Wołoska"
                        },
                        new
                        {
                            IdAddress = 2,
                            City = "Warszawa",
                            PostalCode = "02-324",
                            Street = "Złota"
                        },
                        new
                        {
                            IdAddress = 3,
                            City = "Warszawa",
                            PostalCode = "02-421",
                            Street = "Syta"
                        });
                });

            modelBuilder.Entity("Training_and_diet_backend.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnOrder(0);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Role");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Pupil"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Trainer"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Dietician"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Dietician-Trainer"
                        });
                });

            modelBuilder.Entity("Training_and_diet_backend.Models.TrainerGym", b =>
                {
                    b.Property<int>("IdGym")
                        .HasColumnType("integer");

                    b.Property<int>("IdTrainer")
                        .HasColumnType("integer");

                    b.HasKey("IdGym", "IdTrainer");

                    b.HasIndex("IdTrainer");

                    b.ToTable("Trainer_Gyms");

                    b.HasData(
                        new
                        {
                            IdGym = 1,
                            IdTrainer = 1
                        },
                        new
                        {
                            IdGym = 1,
                            IdTrainer = 2
                        },
                        new
                        {
                            IdGym = 1,
                            IdTrainer = 3
                        },
                        new
                        {
                            IdGym = 1,
                            IdTrainer = 18
                        },
                        new
                        {
                            IdGym = 3,
                            IdTrainer = 16
                        },
                        new
                        {
                            IdGym = 1,
                            IdTrainer = 15
                        },
                        new
                        {
                            IdGym = 2,
                            IdTrainer = 1
                        },
                        new
                        {
                            IdGym = 3,
                            IdTrainer = 1
                        });
                });

            modelBuilder.Entity("TrainingAndDietApp.Domain.Entities.Certificate", b =>
                {
                    b.HasOne("TrainingAndDietApp.Domain.Entities.User", "User")
                        .WithMany("Certificates")
                        .HasForeignKey("IdMentor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TrainingAndDietApp.Domain.Entities.Diet", b =>
                {
                    b.HasOne("TrainingAndDietApp.Domain.Entities.User", "Dietician")
                        .WithMany("DietsAsDietician")
                        .HasForeignKey("IdDietician")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TrainingAndDietApp.Domain.Entities.User", "Pupil")
                        .WithMany("DietsAsPupil")
                        .HasForeignKey("IdPupil");

                    b.Navigation("Dietician");

                    b.Navigation("Pupil");
                });

            modelBuilder.Entity("TrainingAndDietApp.Domain.Entities.Exercise", b =>
                {
                    b.HasOne("TrainingAndDietApp.Domain.Entities.User", "Trainer")
                        .WithMany("Exercises")
                        .HasForeignKey("IdTrainer");

                    b.Navigation("Trainer");
                });

            modelBuilder.Entity("TrainingAndDietApp.Domain.Entities.Gym", b =>
                {
                    b.HasOne("Training_and_diet_backend.Models.Address", "Address")
                        .WithMany("Gyms")
                        .HasForeignKey("IdAddress")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Address");
                });

            modelBuilder.Entity("TrainingAndDietApp.Domain.Entities.Meal", b =>
                {
                    b.HasOne("TrainingAndDietApp.Domain.Entities.User", "Dietician")
                        .WithMany()
                        .HasForeignKey("IdDietician")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dietician");
                });

            modelBuilder.Entity("TrainingAndDietApp.Domain.Entities.MealDiet", b =>
                {
                    b.HasOne("TrainingAndDietApp.Domain.Entities.Diet", "Diet")
                        .WithMany("MealsInDiet")
                        .HasForeignKey("IdDiet")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TrainingAndDietApp.Domain.Entities.Meal", "Meal")
                        .WithMany("Meals")
                        .HasForeignKey("IdMeal")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Diet");

                    b.Navigation("Meal");
                });

            modelBuilder.Entity("TrainingAndDietApp.Domain.Entities.Opinion", b =>
                {
                    b.HasOne("TrainingAndDietApp.Domain.Entities.User", "Mentor")
                        .WithMany("MentorOpinions")
                        .HasForeignKey("IdMentor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TrainingAndDietApp.Domain.Entities.User", "Pupil")
                        .WithMany("PupilOpinions")
                        .HasForeignKey("IdPupil")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mentor");

                    b.Navigation("Pupil");
                });

            modelBuilder.Entity("TrainingAndDietApp.Domain.Entities.PupilMentor", b =>
                {
                    b.HasOne("TrainingAndDietApp.Domain.Entities.User", "Mentor")
                        .WithMany("MentorPupils")
                        .HasForeignKey("IdMentor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TrainingAndDietApp.Domain.Entities.User", "Pupil")
                        .WithMany("PupilMentors")
                        .HasForeignKey("IdPupil")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mentor");

                    b.Navigation("Pupil");
                });

            modelBuilder.Entity("TrainingAndDietApp.Domain.Entities.TraineeExercise", b =>
                {
                    b.HasOne("TrainingAndDietApp.Domain.Entities.Exercise", "Exercise")
                        .WithMany("TraineeExercises")
                        .HasForeignKey("IdExercise")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TrainingAndDietApp.Domain.Entities.TrainingPlan", "TrainingPlan")
                        .WithMany("TraineeExercises")
                        .HasForeignKey("IdTrainingPlan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("TrainingPlan");
                });

            modelBuilder.Entity("TrainingAndDietApp.Domain.Entities.TrainingPlan", b =>
                {
                    b.HasOne("TrainingAndDietApp.Domain.Entities.User", "Pupil")
                        .WithMany("PupilTrainingPlans")
                        .HasForeignKey("IdPupil");

                    b.HasOne("TrainingAndDietApp.Domain.Entities.User", "Trainer")
                        .WithMany("TrainerTrainingPlans")
                        .HasForeignKey("IdTrainer")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pupil");

                    b.Navigation("Trainer");
                });

            modelBuilder.Entity("TrainingAndDietApp.Domain.Entities.User", b =>
                {
                    b.HasOne("Training_and_diet_backend.Models.Role", "Role")
                        .WithMany()
                        .HasForeignKey("IdRole")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Training_and_diet_backend.Models.TrainerGym", b =>
                {
                    b.HasOne("TrainingAndDietApp.Domain.Entities.Gym", "Gym")
                        .WithMany("TrainerGyms")
                        .HasForeignKey("IdGym")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TrainingAndDietApp.Domain.Entities.User", "Trainer")
                        .WithMany("TrainerGyms")
                        .HasForeignKey("IdTrainer")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gym");

                    b.Navigation("Trainer");
                });

            modelBuilder.Entity("TrainingAndDietApp.Domain.Entities.Diet", b =>
                {
                    b.Navigation("MealsInDiet");
                });

            modelBuilder.Entity("TrainingAndDietApp.Domain.Entities.Exercise", b =>
                {
                    b.Navigation("TraineeExercises");
                });

            modelBuilder.Entity("TrainingAndDietApp.Domain.Entities.Gym", b =>
                {
                    b.Navigation("TrainerGyms");
                });

            modelBuilder.Entity("TrainingAndDietApp.Domain.Entities.Meal", b =>
                {
                    b.Navigation("Meals");
                });

            modelBuilder.Entity("TrainingAndDietApp.Domain.Entities.TrainingPlan", b =>
                {
                    b.Navigation("TraineeExercises");
                });

            modelBuilder.Entity("TrainingAndDietApp.Domain.Entities.User", b =>
                {
                    b.Navigation("Certificates");

                    b.Navigation("DietsAsDietician");

                    b.Navigation("DietsAsPupil");

                    b.Navigation("Exercises");

                    b.Navigation("MentorOpinions");

                    b.Navigation("MentorPupils");

                    b.Navigation("PupilMentors");

                    b.Navigation("PupilOpinions");

                    b.Navigation("PupilTrainingPlans");

                    b.Navigation("TrainerGyms");

                    b.Navigation("TrainerTrainingPlans");
                });

            modelBuilder.Entity("Training_and_diet_backend.Models.Address", b =>
                {
                    b.Navigation("Gyms");
                });
#pragma warning restore 612, 618
        }
    }
}
