version: "3.8"
services:
  postgres:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: test
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
